### ISSUE TITLE
polysemy 0.4 fails to build with ghc 8.6.4

### ISSUE THREAD

**Issue by o1lo01ol1o** [adamConnerSax/knit-haskell#6]
Building with stack yields:

```bash
polysemy           > /private/var/folders/tz/4tpc5bgj0659vk61x1ndfhp40000gn/T/stack44329/polysemy-0.4.0.0/src/Polysemy/Internal/TH/Effect.hs:220:25: error:
polysemy           >     Variable not in scope: datatypeInstTypes :: DatatypeInfo -> [Type]                                                      
polysemy           >     |                                                                                                                       
polysemy           > 220 |     case splitAtEnd 2 $ datatypeInstTypes dti of                                                                      
polysemy           >     |    
```

**Comment by o1lo01ol1o** [comment]
(I started to bump the versions in a fork but since I've never used the API, I though you might get there before I do.)

**Comment by adamConnerSax** [comment]
Thanks for opening this!  Sorry I didn't see it until now.  I'll look into it later today, bump versions as appropriate.

**Comment by adamConnerSax** [comment]
Hmm. Using ghc-8.6.4 and pinning polysemy to 0.4.0.0, knit-haskell 0.6.01 still builds for me. Trying again after "cabal v2-update".  But now I have to build pandoc again...
Hmm.  knit-haskell Still builds.  Maybe the error is not ghc-8.6.4/polysemy-0.4.0.0?
Can you replicate on your fork and then I can try to figure out what's happening?

**Comment by o1lo01ol1o** [comment]
I updated `stack` and set `lts-14.0`: now it builds without error.  I dunno, I guess I'll close.  Thx!
